### ISSUE TITLE
Drag & Drop of cards can lead to crashes of the frontend

### ISSUE THREAD

**Issue by Alpa-1** [brisqapp/issue-tracker#63]
### Version 
0.11.3

### Severity
App becomes unusable
A restart of the App is required to fix.

### Steps
- Create a new board
- Create a new list
- Create some cards
- Create a new blank card but leave it in edit mode
- drag any other card - the App is now already in a bad state, visible by the misaligned blue outline around the cards
- keep dragging and dropping cards around and eventually one of them fails

![image](https://github.com/user-attachments/assets/ecd7bce2-c34c-451a-ba99-b0078c56ac38)

![image](https://github.com/user-attachments/assets/bf9ffc0e-6c60-4e6f-a8de-cef54ae567df)

```
TypeError: Cannot read properties of null (reading 'cancelDrop')
    at file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:612437
    at Object.fireRemoveElement (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:620142)
    at Object.unregister (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:610749)
    at Object.dispose (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:620726)
    at n.value (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:553993)
    at bs (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:513063)
    at ks (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:514866)
    at Oc (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:526937)
    at t.unstable_runWithPriority (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:584061)
    at Ko (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:469978)
```

```
TypeError: Cannot set properties of undefined (setting 'cardListId')
    at cL (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:1841271)
    at file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:1836622
    at file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:1770082
    at e.produce (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:1770235)
    at file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:1770036
    at Object.ua [as useReducer] (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:485638)
    at t.useReducer (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:576335)
    at tA (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:1849456)
    at aa (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:484409)
    at Ua (file:///C:/Users/mic/AppData/Local/Programs/Brisqi/resources/app.asar/build/static/js/main.193ad3a7.js:2:493976)
```

**Comment by ashgrover** [comment]
Thanks for reporting this issue. I'm able to reproduce it on my end. It will be fixed in the next release.

**Comment by ashgrover** [comment]
This issue is not resolved in the latest version of the app. Closing the issue.
